version: "3"

services:
  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
    container_name: proxy
    image: diogojunqueirageraldo/fullcycle-nodejs-proxy
    networks:
      - shared-network
    depends_on:
      - server
    ports:
      - "8080:80"

  server:
    container_name: server
    image: diogojunqueirageraldo/fullcycle-nodejs-server
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    entrypoint: wait-for-it --strict -h database -p 3306 -t 60 -- npm start
    environment:
      - SERVER_PORT=3000
      - DB_HOST=database
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=nodedb
    networks:
      - shared-network
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: database
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
    networks:
      - shared-network

networks:
  shared-network:
    driver: bridge
